### ISSUE TITLE
Log littered

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#22] opened 2018-06-14 16:12 UTC
Since I enabled logging, Rompry was littering apache error.log with these messages like this, it went up to 25gb in one day. ANd while this is happening apache2 was going nuts with using cpu at %100 (one of the 4 cores)

I was mostly using Mopidy since yesterday.

```
player/mpd/connection.php on line 88, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996923 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996931 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/connection.php on line 88, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996938 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996945 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/connection.php on line 88, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996952 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996959 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/connection.php on line 88, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996966 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996973 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/connection.php on line 88, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996980 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996987 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/connection.php on line 88, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.996994 2018] [php7:warn] [pid 21778] [client 192.168.1.105:38516] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/
[Thu Jun 14 10:31:05.997027 2018] [php7:error] [pid 21778] [client 192.168.1.105:38516] PHP Fatal error:  Maximum execution time of 800 seconds exceeded in /media/DRIVE/var/www/rompr/player/mpd/sockets.php on line 43, referer: http://192.168.1.100;gc/rompr/

```

**Comment by fatg3erman** [comment] 2018-06-14 17:04
There are several possible explanations for this

* Your setup is completely screwed
* Your player (Mopidy or MPD) has a very short connection timeout set and the connection is closing before Rompr has completed its actions. This is configurable in the config files for both players.
* You are trying to access more than one player from different tabs or windows in the same browser at the same time

Also, if your log file is reaching 25gb then this imples that logrotate is not working on your system. That's not a rompr issue, it's an issue with your distribution and your install of apache.

**Comment by gerroon** [comment] 2018-06-14 17:12
Lets assume my setup is screwed, do you know what could be screewed? Database? Settings?

Do you know where to change those connection time outs?

I have 2 clients open at the same time, one from mobile one from Desktop not sure if that makes difference.

Btw I was not blaming Rompr for the log size, I was just trying to say that it was wriiing insane amounts of lines to the log.

**Comment by gerroon** [comment] 2018-06-14 17:17
Btw I see those lines are starting to show up when I start library scanning in Romry (mopidy). Not sure if this is relevant to the issue.

**Comment by fatg3erman** [comment] 2018-06-14 17:18
The connection timeouts are in your conf files

For mopidy you should have

    [mpd]
    connection_timeout = 60

Or for MPD, somewhere in mpd.conf

    connection_timeout "60"

So long as your two clients are in different browsers or on different machines, you are fine. Don't try to operate two players from the same mchaine at the same time.

I thought I would point out about the log size, because you really need to have logrotate working. I'm very surprised it doesn't work by default.

**Comment by fatg3erman** [comment] 2018-06-14 17:19
If they're coming while scanning the library then the connection timeout is almost certainly the cause. 60 is a minimum (it's in seconds). Try several hundred.

**Comment by gerroon** [comment] 2018-06-14 17:29
Thanks I will try these. The initial log lines are definetely happening while scanning, so I will investigate it further.

**Closed** 2018-06-15 00:30 UTC
