### ISSUE TITLE
FR: Better Online Radio Stuff

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#15] opened 2018-06-12 23:53 UTC
Hi

These are couple issue that I think that can improve the radio experience. Rompr already seems to have some good ideas for radio listening, but ironing out these issues can even make it better.

- http://radio-browser.info/ integration

- Caterories for the Icecast directory

- Removing the station names from the artist or the song or the albums when submitting the current track to the online databases. It seems like some radio names are appended to one of the fields, which naturally makes it impossible to locate the proper media information

- Random radio mode for the personalized radio tab, which pulls from the radio tab.

- Being able to star the currently playing song/artists. Now this is probably sticky situation because at the moment if one stars a playing track from a radio, it is going to star the radio station not the actual media, I am not sure if this is possible but it would be nice. It can even be better to track a separate star field for the stuff from online sources.

These are not my demands or something. I am just bring them up in case the dev or future devs might have interest in these to implement them.

thanks

**Comment by fatg3erman** [comment] 2018-06-13 06:35
In order:

* I'll look into that

* Icecast doesn't provide any way to list by category. Or rather, you can list by category, but you can't get a list of categories so that function is more or less useless. Indeed Icecast doesn't even provide a developer API. You can search for categories, but Icecast's search function sucks. They've been talking about making a Developer API for, ooh, about 5 years. So don't hold your breath :)

* Hmmm. OK

* I'm not sure what you mean. I search for Artist and Track title when a radio station is playing, but I can only go on what the station provides, which is frequently incorrect or mis-spelled. No radio station info is appended to the information, unless you can provide an example otherwise.

* You can already do this. Rating a track from a radio station will add the track to your Wishlist (available from the 'hamburger' above the Info panel. If you have Mopidy with Spotify or Google Play Unlimited, it will search for the track and add it to your Music Collection.

**Comment by fatg3erman** [comment] 2018-06-13 06:36
Sorry, points 3 and 4 should be swapped, I replied in the wrong order :)

**Comment by gerroon** [comment] 2018-06-13 15:02
Hi

See the image file for radio station name being part of the fields.

I am using .m3u radio station listing served by Mopidy or Mpd (same result). I am not using the integrated radio browser (yet)

!(https://filebin.net/txwyark8rzdwy8qj/Selection_019.png?t=vmawvk6u)

**Comment by gerroon** [comment] 2018-06-13 15:37
-Favorites

I tested it with my curated m3u served by Mopidy, I can star the currently playing radio song. WHen I start a song it says searching. But I do not see them listed under any of the stars in the favorites menu. For instance for testing I was giving  5 stars to song from the same radio, and the 5stars fav listing is purely empty.

This is either buggy or not working for .m3u radios as far as I can tell.

**Comment by fatg3erman** [comment] 2018-06-13 16:27
The first point - that is what the radio station is returning as the track title. There's nothing I can do about that. If stations want to mess things up by plastering their branding over everything, listen to other stations :)

Second point -  do you have Spotify or GMusic Unlimited with Mopidy? If not, the track will appear in your Wishlist only. If you do have Spotify or GMusic but the track couldn't be found, it will appear in your Wishlist only. They won't appear anywhere else. The type of radio station makes no difference.

**Comment by gerroon** [comment] 2018-06-13 16:38
@fatg3erman 

I guess that was my original point/feature request, which I did not make it clear I guess. If there was a way to just remove the matching station name from the fields before submitting to online databases.

I do not use any of the online music subscriptions. And I do not know where the wishlist is :) I saw it in the docs but it does nott ell you where it is, sorry if this is a dummy thing to bring it up here.

**Comment by fatg3erman** [comment] 2018-06-13 16:46
That's another of those problems, I could remove it from that specific example but there would be hundreds of other examples that are different, and hundreds of examples where removing a portion of the title would make things worse. There are so many variations on what stations do that it would be impossible to find and test them all.

Most players would simply display radio tracks as a single line : 'Artist - Title' so Rompr does at least attempt to do something helpful :)

The wishlist is on the 'hamburger' menu above the Info panel on the desktop skin. If you have no online music subscriptions then it serves as a reminder to you of tracks that you liked.

**Comment by gerroon** [comment] 2018-06-13 16:56
@fatg3erman 

I see your point about metadata but from the user's perspective it is a harsh sitiation :)

Ok found the wishlist but it is all empty after all favoriting from online radios. Bug?

**Comment by fatg3erman** [comment] 2018-06-13 17:03
Yes it's a harsh situation from the user's perspective, but it is caused by radio stations not following standards. There is a standard way for radio stations to provide metadata - a single field of the type 'Artist - Title'. It has been that way for more than a decade. Sadly I can't do anything if the owners of the stations think their branding is more important than helping their listeners.

The wishlist is working fine for me. Let me look into it some more.

**Comment by fatg3erman** [comment] 2018-06-13 17:07
Can you give me a specific radio station you are listening to where the wishlist thing is not working?

**Comment by gerroon** [comment] 2018-06-13 17:09
Try this.

http://centauri.shoutca.st:8154/

I will test it with other stations too

**Comment by fatg3erman** [comment] 2018-06-13 17:13
That works for me. How are you playing the radio station? List the steps you take to mke it play.

**Comment by gerroon** [comment] 2018-06-13 17:15
- Cd player mode

- Click on an .m3u with radio stations

- Let it play, 

- Star the currently playing song

- Wait until the next song, star that one too

etc

Check the wishlist and the rating/tags menu

**Comment by gerroon** [comment] 2018-06-13 17:19
I wonder if it is an issue with database? See the image for what the Rompry databse looks like

![database] (https://filebin.net/c4zbv9wnt6oz0i21/Selection_021.png?t=wqzvqtd8)

**Comment by gerroon** [comment] 2018-06-13 17:31
I keep my .m3u in the playlist folders set in Mpd and Mopidy. Yopu set that in the configs. Then they show up in the playlists sections in the clients. They are listed in "load  saved playlist" in Rompr


try this as .m3u
```
#EXTM3U
  #EXTINF:0, - DeepTechnoFM
  http://centauri.shoutca.st:8154
  #EXTINF:0, - Proton Radio
  http://protonradio.com:8000/schedule
  #EXTINF:0, - Polushon
  http://38.107.243.188:8591/
  #EXTINF:0, - Anima Amoris [Dub Techno] 320 MP3 anima.sknt.ru
  http://amoris.sknt.ru/dubtechno.mp3
  #EXTINF:0, - Anima Amoris [Deep Tech House] 160 MP3 anima.sknt.ru
  http://amoris.sknt.ru/deeptech.mp3
```

**Comment by fatg3erman** [comment] 2018-06-13 17:36
It works for me, though there is something strange going on with adding radio stations from an m3u. I will investigate further.

Can you try with Soma FM from the Rompr radio stations and rate a track to see what happens?

**Comment by gerroon** [comment] 2018-06-13 18:00
It still does not work. I tried with SomaFM - Black Rock FM

My rating table has only "one entry" and that is a local song. No radio statuon is there

**Comment by fatg3erman** [comment] 2018-06-13 18:11
OK thanks. There is obviously some kind of bug here, but it is going to be hard to find.

A [debug log](https://fatg3erman.github.io/RompR/Troubleshooting#debug-logging) would be very helpful.

**Comment by fatg3erman** [comment] 2018-06-13 18:59
Thanks that's an interesting log but can you try again and this time take it a little slower? There are lots of overlapping things happening and it's hard to trace. Start playing the station, wait for the track to appear, wait for the info panel to update, and then try to rate the track. I only need to see one.

**Comment by fatg3erman** [comment] 2018-06-13 19:44
Actually from that log it looks as if the search for the track is just crashing but I can see no error message. It is possible that your PHP installation is not configured to report PHP errors, so you'll need to change a setting in php.ini

You need to edit the correct php.ini file. You're on debian? It is probably at

    /etc/php/7.0/apache2/php.ini

Although the 7.0 may change depending on which version of PHP you're using. You need to find this section

```
; Besides displaying errors, PHP can also log errors to locations such as a
; server-specific log, STDERR, or a location specified by the error_log
; directive found below. While errors should not be displayed on productions
; servers they should still be monitored and logging is a great way to do that.
; Default Value: Off
; Development Value: On
; Production Value: On
; http://php.net/log-errors
log_errors = On

```

log_errors needs to be set to On.

Also

```
; Common Values:
;   E_ALL (Show all errors, warnings and notices including coding standards.)
;   E_ALL & ~E_NOTICE  (Show all errors, except for notices)
;   E_ALL & ~E_NOTICE & ~E_STRICT  (Show all errors, except for notices and coding standards warnings.)
;   E_COMPILE_ERROR|E_RECOVERABLE_ERROR|E_ERROR|E_CORE_ERROR  (Show only errors)
; Default Value: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
; Development Value: E_ALL
; Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
; http://php.net/error-reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

```
The value of error_reporting must be as shown here

Then if you can send another debug log it will help more.

**Comment by fatg3erman** [comment] 2018-06-13 19:56
Oh also check for the

    error_log

value. Make sure it is set to nothing by putting a ; in front of it

**Comment by gerroon** [comment] 2018-06-14 19:58
Hi

I was trying to set this up so I could give you logs but now it stars ok  from online radios:( I am still testing this. 

I restarted my apache and mysql server couple times, not sure if they borked in the background.  

It seems to work as expected, ifthe song is in the database, it is starred if not it is in the wishlish. But again, I am still testing. I want to see why and when it borked before.

Lets assume that it works initally, I have one feature to ask for.

- Show some kind of icon/name where the starred song from when it was starrred, is it local, is it online radio, name of the radio maybe, date ? I think this can help for relocating the song, and can be  like a bit of listening journal thing, see when and how all those stars and wishlist originated.

**Comment by fatg3erman** [comment] 2018-06-14 20:49
I like your idea. I'm going to create a separate Issue for it. One Issue per idea makes them easier to track and easier to close.

**Comment by gerroon** [comment] 2018-06-14 20:59
Cool, thanks for consider.  

I normally take a screenshot on my phoeen while listening radio to keep track of things I like, but the starring and implementing the FR will take this to the next level.

**Comment by fatg3erman** [comment] 2018-06-17 09:50
Closing because this contains multiple feature requests. One request per Issue please. I'm making a new one for the http://radio-browser.info/ integration

**Closed by fatg3erman** 2018-06-17 09:50 UTC
